### ISSUE TITLE
quaternion_matrix function

### ISSUE THREAD

**Issue by swiz23** [DLu/tf_transformations#2]
Hi,

For the 'quaternion_matrix' function, you mention in the comments (in the code), that it returns a homogeneous rotation matrix, but in reality, it's returning a 4x4 transformation matrix. Is there any reason it's not just returning a 3x3 rotation matrix?

FYI - thanks for developing this library!!

**Comment by hodnajit** [comment]
homogeneous rotation matrix means 4x4 transformation matrix with translation part identity --> it is transform, but it only consists of rotation, no translation

See this [https://www.researchgate.net/profile/Alexandre-Campo/publication/315552592/figure/fig2/AS:705739689566214@1545272862838/Homogeneous-Transformation-Matrix-a-and-Global-Homogeneous-Transformation-Matrix-b.ppm](image)

I think the reason is, that this library is general from transformations, if you want to use quat2mat conversion, you can use transforms3d library directly :)

**Comment by DLu** [comment]
[code reference](https://github.com/DLu/tf_transformations/blob/0cb2cff35b732793d3df8e7aa95934560cc1d71b/tf_transformations/__init__.py#L785)

The comment is based on [this upstream code](https://github.com/ros/geometry/blob/8be1f625144eba8a46b83eb7fdc24aaabf11e565/tf/src/tf/transformations.py#L1175). I'm not an expert on the naming of matrices, but for backwards compatibility reasons, I will not change the return type. If there's a better name other than "homogenous rotation matrix" for the comments, I'm open to suggestions.

**Comment by swiz23** [comment]
Hi @hodnajit,

I tried accessing the link you posted, but it just redirects me to https://github.com/DLu/tf_transformations/issues/image. Could you quote the relevant text?

@DLu,
I think updating the comment to `Return 4x4 homogenous rotation matrix from quaternion` would be helpful!

**Comment by DLu** [comment]
https://github.com/DLu/tf_transformations/commit/9cdf02a10246cf606552bfe80944221f0187ee66
